components:
    schemas:
        UserAccount:
            description:
                Represents a user.
            properties:
                birthDate:
                    description:
                        The user's date of birth, in ISO 8601 format.
                    format: date-time
                    type: string
                dateCreated:
                    description:
                        The creation date of the user's account.
                    format: date-time
                    type: string
                dateModified:
                    description:
                        The last time any field of the user's account was changed.
                    format: date-time
                    type: string
                emailAddress:
                    description:
                        The user's main email address.
                    type: string
                firstName:
                    description:
                        The user's first name.
                    type: string
                id:
                    description:
                        The user's ID.
                    format: int64
                    readOnly: true
                    type: integer
                jobTitle:
                    description:
                        The user's job title.
                    type: string
                languageId:
                    description:
                        The user's language.
                    type: string
                lastName:
                    description:
                        The user's surname (last name).
                    type: string
                male:
                    description:
                        The user's gender.
                    readOnly: true
                    type: boolean
                middleName:
                    description:
                        The user's additional name (e.g., middle name).
                    type: string
                name:
                    description:
                        The user's full name.
                    type: string
                password:
                    description:
                        The user's encrypted password.
                    type: string
                    writeOnly: true
                screenName:
                    description:
                        The user's alias or screen name.
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.headless.osb.commerce.client', and version '1.0.0'.. A Java client JAR is available for use with
        the group ID 'com.liferay', artifact ID 'com.liferay.headless.osb.commerce.portal.instance.client', and version
        '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Headless OSB Commerce"
    version: v1.0
openapi: 3.0.1
paths:
    "/user-accounts/{portalInstanceId}":
        post:
            description:
                Creates a new user account
            operationId: postUserAccount
            parameters:
                - in: path
                  name: portalInstanceId
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UserAccount"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/UserAccount"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/UserAccount"
                    description:
                        ""